/*CREATE DATABASE TEST2705 --СОЗДАНИЕ БАЗЫ ТАБЛИЦЫ

USE TEST2705 -- ПЕРЕКЛЮЧЕНИЕ НА БАЗЗУ ДАННЫХ

CREATE TABLE BOOKS(
ID INT NOT NULL,
BOOK_NAME NVARCHAR(100) NOT NULL,
AUTOR NVARCHAR(100)NOT NULL,
PUBLISHING NVARCHAR(100),
AMMOUNT_OF_PAGES INT,
PEREPLET BIT,
YEAR_OF_PUBLISHING DATE
CONSTRAINT UC_BOOKNAME UNIQUE (BOOK_NAME)
);

ALTER TABLE BOOKS --ИЗМИНЕНИЕ ТАБЛИЦЫ 
ADD TIRAZH INT		-- ДОБАВИТЬ СТОЛБИК

ALTER TABLE BOOKS		--ИЗМИНЕНИЕ ТАБЛИЦЫ 
DROP COLUMN TIRAZH		-- УДАЛЕНИЕ СТОЛБИК

ALTER TABLE BOOKS						--ИЗМИНЕНИЕ ТАБЛИЦЫ 
ALTER COLUMN PEREPLET NVARCHAR(10)		-- ИЗМИНЕНИЕ СТОЛБЦА

DROP TABLE BOOKS  -- УДАЛЕНИЕ ТАБЛИЦЫ

ALTER TABLE BOOKS						--ИЗМИНЕНИЕ ТАБЛИЦЫ 
ALTER COLUMN PEREPLET BIT NOT NULL;		-- ИЗМИНЕНИЕ МОДФИКАТОРА

ALTER TABLE BOOKS						--ИЗМИНЕНИЕ ТАБЛИЦЫ 
ADD UNIQUE (AUTOR)		                   -- ИЗМИНЕНИЕ МОДИФИКАТОРА НА УНИКАЛЬНЫЙ

ALTER TABLE BOOKS						--ИЗМИНЕНИЕ ТАБЛИЦЫ 
ALTER COLUMN ID INT NOT NULL;

ALTER TABLE BOOKS						--ИЗМИНЕНИЕ ТАБЛИЦЫ 
ADD PRIMARY KEY (ID)

*/
CREATE DATABASE HOSPITAL
USE HOSPITAL

CREATE TABLE DEPARTMENTS(
DEPARTMENTS_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
BUILDING INT NOT NULL  CHECK (BUILDING >= 1 AND BUILDING <= 5),
FINANCING MONEY NOT NULL CHECK(FINANCING >=0) DEFAULT 0,
NAME NVARCHAR(100) NOT NULL DEFAULT'NONE' UNIQUE,
)
CREATE TABLE DISEASES(
DISEASES_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
DISEASES_NAME NVARCHAR(100) NOT NULL DEFAULT 0 UNIQUE,
SEVERITY INT NOT NULL CHECK(SEVERITY >=1) DEFAULT 0,
)

CREATE TABLE DOCTORS(
DOCTORS_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
NAME NVARCHAR(MAX) NOT NULL DEFAULT 0,
PHONE CHAR(10) NOT NULL,
SALARY MONEY NOT NULL CHECK(SALARY >0),
SURNAME NVARCHAR(MAX) NOT NULL DEFAULT 0
)

CREATE TABLE EXAMINATIONS(
EXAMINATIONS_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
EXAMINATIONS_DAYOFWEEK INT NOT NULL CHECK(EXAMINATIONS_DAYOFWEEK >=1 AND EXAMINATIONS_DAYOFWEEK<= 7),
EXAMINATIONS_NAME  NVARCHAR(100) NOT NULL DEFAULT 0,
START_TIME INT NOT NULL CHECK(START_TIME > 8 AND START_TIME < 18),
ENDTIME INT NOT NULL 
)
CREATE TABLE PATIENTS(
PATIENTS_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
PAT_NAME NVARCHAR(100) NOT NULL,
EXAMINATIONS_ID INT REFERENCES  EXAMINATIONS(EXAMINATIONS_ID),
DOCTORS_ID INT REFERENCES  DOCTORS(DOCTORS_ID),
DEPARTMENTS_ID INT REFERENCES  DEPARTMENTS(DEPARTMENTS_ID),
DISEASES_ID INT REFERENCES  DISEASES(DISEASES_ID),
NUMBER NVARCHAR(100) UNIQUE,
)
ALTER TABLE EXAMINATIONS
ADD CONSTRAINT C12 CHECK(ENDTIME > START_TIME )


INSERT INTO DOCTORS
VALUES ('MAXIM','0961014124',400,'TCHAR')

INSERT INTO DOCTORS
VALUES ('IVAN','05867124',600,'IVANOV')

INSERT INTO DOCTORS
VALUES ('DENIS','094723813',900,'SIDOROV')

INSERT INTO DOCTORS
VALUES ('SERGEY','0123456',123,'DOROFEEV')

INSERT INTO DEPARTMENTS
VALUES (1,50000,'EMINEM')

INSERT INTO DEPARTMENTS
VALUES (3,4000,'CHAK')

INSERT INTO DEPARTMENTS
VALUES (2,500,'VEIDER')

INSERT INTO DEPARTMENTS
VALUES (5,200,'ROTOR')

INSERT INTO DISEASES
VALUES ('MAXIM',2)

INSERT INTO DISEASES
VALUES ('ULIK',1)

INSERT INTO DISEASES
VALUES ('SIDOR',4)

INSERT INTO DISEASES
VALUES ('JORJU',1)

INSERT INTO EXAMINATIONS
VALUES (1,'USIK',9,10)

INSERT INTO EXAMINATIONS
VALUES (1,'FEN',9,40)

INSERT INTO EXAMINATIONS
VALUES (7,'CHESTER',17,19)
											
INSERT INTO EXAMINATIONS					
VALUES (5,'DERECHABL',12,16)				
											
INSERT INTO EXAMINATIONS					
VALUES (3,'WALLIE',10,19)	

INSERT INTO PATIENTS					
VALUES ('VIKTOR',1,1,1,1)
			
INSERT INTO PATIENTS					
VALUES ('ELENA',2,1,2,1,096727891)

INSERT INTO PATIENTS					
VALUES ('MAX',3,3,2,4,08217827839)

INSERT INTO PATIENTS					
VALUES ('VLAD',3,1,2,1,0668124238)

INSERT INTO PATIENTS					
VALUES ('GEROU',5,1,2,1,055123321)

SELECT * FROM DEPARTMENTS					
SELECT * FROM DOCTORS						
SELECT * FROM DISEASES						
SELECT * FROM EXAMINATIONS
SELECT * FROM PATIENTS

-- ИМЯ СОДЕРЖИТ A C D  ФАМИЛИЯ > 5 СИМВОЛОВ
SELECT * FROM DOCTORS
WHERE NAME LIKE '%A%'OR NAME LIKE '%B%'OR NAME LIKE '%D%'OR SURNAME LIKE '%_____%'

-- DZ!!!
SELECT * FROM PATIENTS

SELECT NAME,BUILDING, PAT_NAME
FROM DEPARTMENTS, PATIENTS
WHERE PATIENTS.DEPARTMENTS_ID = DEPARTMENTS.DEPARTMENTS_ID

SELECT NAME 
FROM DEPARTMENTS

SELECT PAT_NAME AS PATIENTS, START_TIME 
FROM PATIENTS, EXAMINATIONS
WHERE PATIENTS.EXAMINATIONS_ID = EXAMINATIONS.EXAMINATIONS_ID AND ENDTIME >30;

SELECT PAT_NAME AS PATIENTS, START_TIME 
FROM PATIENTS, EXAMINATIONS
WHERE PATIENTS.EXAMINATIONS_ID = EXAMINATIONS.EXAMINATIONS_ID AND ENDTIME < GETDATE();

SELECT PAT_NAME AS PATIENTS, START_TIME 
FROM PATIENTS, EXAMINATIONS
WHERE PATIENTS.EXAMINATIONS_ID = EXAMINATIONS.EXAMINATIONS_ID AND ENDTIME < 12 AND START_TIME >9;

SELECT PAT_NAME AS PATIENTS, BUILDING
FROM PATIENTS, DEPARTMENTS
WHERE PATIENTS.DEPARTMENTS_ID = DEPARTMENTS.DEPARTMENTS_ID AND BUILDING <=3;

SELECT PAT_NAME FROM PATIENTS
WHERE PAT_NAME LIKE 'P%'

/*
■■ вывести данные о пациентах, которых лечит опреде-
ленный врач с одинаковыми заболеваниями;
■■ получить данные о пациентах, пользующихся услу-
гами определенного мобильного оператора;
■■ переименовать название определенного отделения;
■■ удалить всех пациентов, которые были выписаны
больше чем полгода назад.*/

SELECT PATIENTS_ID, PAT_NAME, EXAMINATIONS_ID, DEPARTMENTS_ID, DISEASES_ID, NAME
FROM PATIENTS, DOCTORS
WHERE PATIENTS.DOCTORS_ID = 1 AND PATIENTS.DISEASES_ID = 1 AND PATIENTS.DOCTORS_ID = DOCTORS.DOCTORS_ID

SELECT * FROM PATIENTS
WHERE NUMBER LIKE '96%' OR  NUMBER LIKE '66%'

UPDATE DEPARTMENTS 
SET NAME = 'ZOSH'
WHERE DEPARTMENTS_ID = 1

